# Main configuration
project_name:
  description: "Name of the project and of the dataset directory"
  value: "amsterdam24"

webapp_login: 
  description: "SSH login of the webapp server"
  value: "admin@invibe.nohost.me"

webapp_dir: 
  description: "Directory of the web app server"
  value: "/var/www/my_webapp"

cluster_name: 
  description: "Name of the cluster to use in AMU mesocenter"
  value: "skylake"

# Dataset description
subjects:
  description: "Subjects of the dataset"
  value: ["sub-01", "sub-02", "sub-03"]

sessions:
  description: "Sessions of the dataset"
  value: ["ses-01", "ses-02", "ses-03", "ses-04", "ses-05", "ses-06", "ses-07", "ses-08"]

task_names: 
  description: "Names of the tasks of the dataset"
  value: ["pRF", "pRFoccl", "pRFaniso", "pRFstrab", "RSC", "RSR", "RSL", "CAL"]

func_session:
  description: "Session containing the pRF tasks"
  value: ["ses-06"] #TODO

prf_task_names:
  description: "Names of the tasks analysed with pRF methods"
  value: ["pRF", "pRFoccl", "pRFaniso", "pRFstrab"]

partial_scan: 
  description: "Dataset including non whole-head recording"
  value: False
  levels: [True, False]

TR: 
  description: "Time repetition of the pRF tasks"
  unit: "seconds"
  value: 1.6

TRs: 
  description: "Number of TR of the pRF task"
  value: 188
  
# Preprocessing
preproc_prep: 
  description: "Name of the main preprocessing method"
  value: "fmriprep"

flattening_method:
  description: "Method use to obtain cortical flat maps"
  value: "autoflatten"
  levels: ["autoflatten", "mrisflatten", "autoflatten_freesurfer"]
  level-description: 
    autoflatten: "Use autoflatten software for automatic flattening using pyflatten"
    mris_flatten: "Use mrisflatten after cutting manually the cortex with freesurfer"
    autoflatten_freesurfer: "Use autoflatten software for automatic flattening using freesurfer mrisflatten"

normalization: 
  description : "Name of the preprocessing normalization step (e.g. z-score, %-change)"
  value: "z-score"

filtering:
  description: "Name of the preprocessing high-pass filtering step (e.g. dct for discrete cosine transform)"
  value: "dct"

high_pass_threshold: 
  description: "Frequency (in Hz) below which signals are attenuated or removed."
  value: 0.01

formats: 
  description: "Data format label names after preprocessing"
  value: ["fsnative", "170k"]

extensions: 
  description: "Data format extensions after preprocessing"
  value: ["func.gii", "dtseries.nii"]

formats_conversion: 
  description: "Correspondance between full brain format (e.g. 170k, 91k) and cortex only (e.g. 59k, 64k)"
  value: 
      "170k": "59k"
      "91k": "32k"

pycortex_subject_template:
  description: "HCP subject use as template for pycortex projection (e.g. sub-hcp1.6mm or sub-hcp2.0mm"
  value: "sub-hcp1.6mm"

averaging_templates:
  description: "Templates on whiche subject will be averaged. The key is the template name, the value is the format"
  value: 
    "hcp1.6mm" : "170k"

maps_names_corr: 
  description: "Inter-run correlation maps names of gifti files"
  value: ["slope", "intercept", "rvalue", "pvalue", "stderr", "trs", "corr_pvalue_5pt", "corr_pvalue_1pt"]

# Stats
fdr_alpha: 
  description: "P value level list for FDR corrected statistics"
  value: [0.05, 0.01]

corr_stats_th: 
  description: "p value minimum threshold for inter-run correlation analysis"
  value: 0.05